basePath: /
definitions:
  auth_handlers.LoginRequest:
    description: Login request payload
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth_handlers.RegisterRequest:
    description: Registration request payload
    properties:
      email:
        type: string
      password:
        minLength: 3
        type: string
    required:
    - email
    - password
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.LoginResponse:
    properties:
      token:
        type: string
      user:
        properties:
          email:
            type: string
          id:
            type: integer
          tier:
            type: string
        type: object
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.ProfileResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      tier:
        type: string
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.RegisterResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      tier:
        type: string
    type: object
  github_com_nazrawigedion123_wallet-backend_auth_models.TierUpgradeResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      tier:
        type: string
    type: object
  github_com_nazrawigedion123_wallet-backend_wallet_models.SimulationOptions:
    properties:
      count:
        description: e.g., up to 1 million
        type: integer
      include_failed:
        type: boolean
      output_to_csv:
        type: boolean
      tier_distribution:
        description: assign tiers randomly
        type: boolean
      transaction_types:
        items:
          type: string
        type: array
    type: object
  github_com_nazrawigedion123_wallet-backend_webhook_models.IncomingWebhook:
    properties:
      amount:
        type: number
      event_id:
        type: string
      metadata:
        $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_webhook_models.Metadata'
      status:
        type: string
      timestamp:
        type: string
      type:
        type: string
      user_id:
        type: string
    required:
    - amount
    - event_id
    - status
    - type
    - user_id
    type: object
  github_com_nazrawigedion123_wallet-backend_webhook_models.Metadata:
    properties:
      transactionID:
        type: integer
    type: object
  wallet_handlers.TransactionRequest:
    properties:
      amount:
        type: number
    required:
    - amount
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a wallet backend server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wallet Backend API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Login a new user account
      parameters:
      - description: Registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
      summary: Login a new user
      tags:
      - auth
  /api/logout:
    post:
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.LogoutResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
  /api/profile:
    get:
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /api/tiers/upgrade:
    post:
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.TierUpgradeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_auth_models.ErrorResponse'
  /simulate/status:
    get:
      description: Returns the current status of background simulations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get simulation status
      tags:
      - Simulation
  /simulate/transactions:
    post:
      description: Starts a background process to generate simulated transactions
      parameters:
      - description: Simulation options
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_wallet_models.SimulationOptions'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Simulate transactions
      tags:
      - Simulation
  /simulate/users:
    post:
      description: Starts a background process to generate simulated users
      parameters:
      - description: Simulation options
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_wallet_models.SimulationOptions'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Simulate user creation
      tags:
      - Simulation
  /wallet/balance:
    get:
      description: Returns the wallet balance for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user wallet balance
      tags:
      - Wallet
  /wallet/deposit:
    post:
      description: it deposits a to transaction and adds money to balance
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Deposit to wallet
      tags:
      - Wallet
  /wallet/transactions:
    get:
      description: Retrieves the transaction history for the user's wallet
      parameters:
      - description: Filter by transaction type
        in: query
        name: type
        type: string
      - description: Filter by transaction status
        in: query
        name: status
        type: string
      - description: Limit number of transactions (default 50)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get transaction history
      tags:
      - Wallet
  /wallet/withdraw:
    post:
      description: Withdraws money from the wallet balance
      parameters:
      - description: Withdrawal request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/wallet_handlers.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Withdraw from wallet
      tags:
      - Wallet
  /webhook:
    post:
      consumes:
      - application/json
      description: Handles and processes incoming webhook payloads
      parameters:
      - description: Webhook payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_nazrawigedion123_wallet-backend_webhook_models.IncomingWebhook'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Returns error details
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Duplicate webhook event
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Process incoming webhook
      tags:
      - Webhooks
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
